// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (white_player_id, black_player_id, pgn, result, time_control)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, white_player_id, black_player_id, pgn, result, time_control, created_at, updated_at
`

type CreateGameParams struct {
	WhitePlayerID pgtype.UUID `json:"white_player_id"`
	BlackPlayerID pgtype.UUID `json:"black_player_id"`
	Pgn           string      `json:"pgn"`
	Result        pgtype.Text `json:"result"`
	TimeControl   pgtype.Int4 `json:"time_control"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.WhitePlayerID,
		arg.BlackPlayerID,
		arg.Pgn,
		arg.Result,
		arg.TimeControl,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.Pgn,
		&i.Result,
		&i.TimeControl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games
WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const getGame = `-- name: GetGame :one
SELECT id, white_player_id, black_player_id, pgn, result, time_control, created_at, updated_at FROM games
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.Pgn,
		&i.Result,
		&i.TimeControl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGames = `-- name: ListGames :many
SELECT id, white_player_id, black_player_id, pgn, result, time_control, created_at, updated_at FROM games
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListGamesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListGames(ctx context.Context, arg ListGamesParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGames, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.WhitePlayerID,
			&i.BlackPlayerID,
			&i.Pgn,
			&i.Result,
			&i.TimeControl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGames = `-- name: ListUserGames :many
SELECT id, white_player_id, black_player_id, pgn, result, time_control, created_at, updated_at FROM games
WHERE white_player_id = $1 OR black_player_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserGamesParams struct {
	WhitePlayerID pgtype.UUID `json:"white_player_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

func (q *Queries) ListUserGames(ctx context.Context, arg ListUserGamesParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, listUserGames, arg.WhitePlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.WhitePlayerID,
			&i.BlackPlayerID,
			&i.Pgn,
			&i.Result,
			&i.TimeControl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :one
UPDATE games
SET pgn = $2, result = $3
WHERE id = $1
RETURNING id, white_player_id, black_player_id, pgn, result, time_control, created_at, updated_at
`

type UpdateGameParams struct {
	ID     pgtype.UUID `json:"id"`
	Pgn    string      `json:"pgn"`
	Result pgtype.Text `json:"result"`
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGame, arg.ID, arg.Pgn, arg.Result)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.Pgn,
		&i.Result,
		&i.TimeControl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
