// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID            pgtype.UUID      `json:"id"`
	WhitePlayerID pgtype.UUID      `json:"white_player_id"`
	BlackPlayerID pgtype.UUID      `json:"black_player_id"`
	Pgn           string           `json:"pgn"`
	Result        pgtype.Text      `json:"result"`
	TimeControl   pgtype.Int4      `json:"time_control"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Move struct {
	ID         pgtype.UUID `json:"id"`
	GameID     pgtype.UUID `json:"game_id"`
	MoveNumber int32       `json:"move_number"`
	Side       string      `json:"side"`
	MoveSan    string      `json:"move_san"`
	MoveUci    string      `json:"move_uci"`
	Fen        string      `json:"fen"`
	TimeTaken  pgtype.Int4 `json:"time_taken"`
}

type User struct {
	ID        pgtype.UUID      `json:"id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	Rating    pgtype.Int4      `json:"rating"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
