// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moves.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMove = `-- name: CreateMove :one
INSERT INTO moves (game_id, move_number, side, move_san, move_uci, fen, time_taken)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, game_id, move_number, side, move_san, move_uci, fen, time_taken
`

type CreateMoveParams struct {
	GameID     pgtype.UUID `json:"game_id"`
	MoveNumber int32       `json:"move_number"`
	Side       string      `json:"side"`
	MoveSan    string      `json:"move_san"`
	MoveUci    string      `json:"move_uci"`
	Fen        string      `json:"fen"`
	TimeTaken  pgtype.Int4 `json:"time_taken"`
}

func (q *Queries) CreateMove(ctx context.Context, arg CreateMoveParams) (Move, error) {
	row := q.db.QueryRow(ctx, createMove,
		arg.GameID,
		arg.MoveNumber,
		arg.Side,
		arg.MoveSan,
		arg.MoveUci,
		arg.Fen,
		arg.TimeTaken,
	)
	var i Move
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.MoveNumber,
		&i.Side,
		&i.MoveSan,
		&i.MoveUci,
		&i.Fen,
		&i.TimeTaken,
	)
	return i, err
}

const deleteGameMoves = `-- name: DeleteGameMoves :exec
DELETE FROM moves
WHERE game_id = $1
`

func (q *Queries) DeleteGameMoves(ctx context.Context, gameID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGameMoves, gameID)
	return err
}

const getMove = `-- name: GetMove :one
SELECT id, game_id, move_number, side, move_san, move_uci, fen, time_taken FROM moves
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMove(ctx context.Context, id pgtype.UUID) (Move, error) {
	row := q.db.QueryRow(ctx, getMove, id)
	var i Move
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.MoveNumber,
		&i.Side,
		&i.MoveSan,
		&i.MoveUci,
		&i.Fen,
		&i.TimeTaken,
	)
	return i, err
}

const listGameMoves = `-- name: ListGameMoves :many
SELECT id, game_id, move_number, side, move_san, move_uci, fen, time_taken FROM moves
WHERE game_id = $1
ORDER BY move_number ASC
`

func (q *Queries) ListGameMoves(ctx context.Context, gameID pgtype.UUID) ([]Move, error) {
	rows, err := q.db.Query(ctx, listGameMoves, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Move{}
	for rows.Next() {
		var i Move
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.MoveNumber,
			&i.Side,
			&i.MoveSan,
			&i.MoveUci,
			&i.Fen,
			&i.TimeTaken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
