// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreateMove(ctx context.Context, arg CreateMoveParams) (Move, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteGame(ctx context.Context, id pgtype.UUID) error
	DeleteGameMoves(ctx context.Context, gameID pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetGame(ctx context.Context, id pgtype.UUID) (Game, error)
	GetMove(ctx context.Context, id pgtype.UUID) (Move, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListGameMoves(ctx context.Context, gameID pgtype.UUID) ([]Move, error)
	ListGames(ctx context.Context, arg ListGamesParams) ([]Game, error)
	ListUserGames(ctx context.Context, arg ListUserGamesParams) ([]Game, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
