package handlers

import (
	"context"
	"fmt"
	"log"

	"github.com/ankits1626/chess-coach-backend/internal/database"
	"github.com/ankits1626/chess-coach-backend/internal/websocket"
	"github.com/jackc/pgx/v5/pgtype"
)

// CreateGameHandler handles game creation.
type CreateGameHandler struct {
	manager *GameManager
}

// Handle implements ActionHandler.Handle.
//
// Request format:
//
//	{
//	  "id": "req-123",
//	  "type": "request",
//	  "action": "createGame",
//	  "data": {
//	    "timeControl": "5+0"
//	  }
//	}
func (h *CreateGameHandler) Handle(ctx context.Context, client *websocket.Client, msg *websocket.Message) error {
	// 1. Extract and validate time control
	timeControl, err := websocket.RequireString(msg.Data, "timeControl")
	if err != nil {
		return err
	}

	seconds, err := websocket.ValidateTimeControl(timeControl)
	if err != nil {
		return fmt.Errorf("invalid time control: %w", err)
	}

	// 2. Generate game ID
	gameID := websocket.GenerateUUID()
	gameIDStr := websocket.UUIDToString(gameID)

	log.Printf("CreateGame: Creating game %s for user %s with time control %s (%ds)",
		gameIDStr, client.UserID, timeControl, seconds)

	// 3. Validate white player ID
	whitePlayerUUID := websocket.StringToUUID(client.UserID)
	if !whitePlayerUUID.Valid {
		return fmt.Errorf("invalid user ID")
	}

	// 4. Create game in database (ID auto-generated by database)
	game, err := h.manager.GetDB().CreateGame(ctx, database.CreateGameParams{
		WhitePlayerID: whitePlayerUUID,
		BlackPlayerID: pgtype.UUID{Valid: false}, // NULL - waiting
		Pgn:           "",
		Result:        websocket.StringToText("*"),
		TimeControl:   websocket.IntToInt4(seconds),
	})
	if err != nil {
		log.Printf("CreateGame: Database error: %v", err)
		return fmt.Errorf("failed to create game")
	}

	// 5. Use the database-generated game ID
	gameIDStr = websocket.UUIDToString(game.ID)
	log.Printf("CreateGame: Database generated game ID: %s", gameIDStr)

	// 6. Add to pending games
	h.manager.CreatePendingGame(gameIDStr, client, timeControl)

	// 6. Set client's game ID
	client.SetGameID(gameIDStr)

	log.Printf("CreateGame: Game %s created successfully, waiting for opponent", gameIDStr)

	// 7. Send success response
	websocket.SendSuccessResponse(client, msg.ID, map[string]interface{}{
		"gameId":      gameIDStr,
		"status":      "waiting",
		"side":        "white",
		"timeControl": timeControl,
		"fen":         h.manager.GetChessService().GetStartingPosition(),
	})

	return nil
}
