package handlers

import (
	"context"
	"fmt"
	"log"

	"github.com/ankits1626/chess-coach-backend/internal/database"
	"github.com/ankits1626/chess-coach-backend/internal/websocket"
	"github.com/ankits1626/chess-coach-backend/internal/websocket/handlers/player"
	"github.com/jackc/pgx/v5/pgtype"
)

// CreateGameHandler handles game creation.
type CreateGameHandler struct {
	manager *GameManager
}

// Handle implements ActionHandler.Handle.
//
// Request format:
//
//	{
//	  "id": "req-123",
//	  "type": "request",
//	  "action": "createGame",
//	  "data": {
//	    "timeControl": "5+0"
//	  }
//	}
func (h *CreateGameHandler) Handle(ctx context.Context, client *websocket.Client, msg *websocket.Message) error {
	// 1. Extract and validate parameters
	timeControl, err := websocket.RequireString(msg.Data, "timeControl")
	if err != nil {
		return err
	}

	// Extract mode (default: humanVsComputer)
	modeStr, ok := msg.Data["mode"].(string)
	if !ok || modeStr == "" {
		modeStr = "humanVsComputer"
	}
	mode := player.GameMode(modeStr)
	if err := mode.Validate(); err != nil {
		return fmt.Errorf("invalid game mode: %w", err)
	}

	// Extract difficulty (default: medium)
	difficulty, ok := msg.Data["difficulty"].(string)
	if !ok || difficulty == "" {
		difficulty = "medium"
	}

	// Extract playerColor (default: white)
	playerColor, ok := msg.Data["playerColor"].(string)
	if !ok || playerColor == "" {
		playerColor = "white"
	}
	if playerColor != "white" && playerColor != "black" {
		return fmt.Errorf("invalid playerColor: must be 'white' or 'black'")
	}

	seconds, err := websocket.ValidateTimeControl(timeControl)
	if err != nil {
		return fmt.Errorf("invalid time control: %w", err)
	}

	// 2. Generate game ID
	gameID := websocket.GenerateUUID()
	gameIDStr := websocket.UUIDToString(gameID)

	log.Printf("CreateGame: Creating game %s for user %s as %s with time control %s (%ds)",
		gameIDStr, client.UserID, playerColor, timeControl, seconds)

	// 3. Validate user ID and determine database IDs based on chosen color
	userUUID := websocket.StringToUUID(client.UserID)
	if !userUUID.Valid {
		return fmt.Errorf("invalid user ID")
	}

	var whitePlayerUUID, blackPlayerUUID pgtype.UUID
	if playerColor == "white" {
		whitePlayerUUID = userUUID
		blackPlayerUUID = pgtype.UUID{Valid: false} // Computer (or NULL for human vs human)
	} else {
		whitePlayerUUID = pgtype.UUID{Valid: false} // Computer (or NULL for human vs human)
		blackPlayerUUID = userUUID
	}

	// 4. Create game in database (ID auto-generated by database)
	game, err := h.manager.GetDB().CreateGame(ctx, database.CreateGameParams{
		WhitePlayerID: whitePlayerUUID,
		BlackPlayerID: blackPlayerUUID,
		Pgn:           "",
		Result:        websocket.StringToText("*"),
		TimeControl:   websocket.IntToInt4(seconds),
	})
	if err != nil {
		log.Printf("CreateGame: Database error: %v", err)
		return fmt.Errorf("failed to create game")
	}

	// 5. Use the database-generated game ID
	gameIDStr = websocket.UUIDToString(game.ID)
	log.Printf("CreateGame: Database generated game ID: %s", gameIDStr)

	// 6. Add to pending games with player color
	if err := h.manager.CreatePendingGame(gameIDStr, mode, client, difficulty, playerColor, timeControl); err != nil {
		log.Printf("CreateGame: Failed to create pending game: %v", err)
		return fmt.Errorf("failed to create pending game: %w", err)
	}

	// 7. Set client's game ID
	client.SetGameID(gameIDStr)

	// 8. For modes that don't need a second human player, auto-activate
	if mode == player.GameModeHumanVsComputer {
		log.Printf("CreateGame: Auto-activating computer game %s", gameIDStr)

		// Pass client as blackClient if player chose black, otherwise nil
		var blackClient *websocket.Client
		if playerColor == "black" {
			blackClient = client
		}

		activeGame, err := h.manager.ActivateGame(gameIDStr, blackClient)
		if err != nil {
			log.Printf("CreateGame: Failed to activate game: %v", err)
			return fmt.Errorf("failed to activate game: %w", err)
		}

		// Send success response for active game
		websocket.SendSuccessResponse(client, msg.ID, map[string]interface{}{
			"gameId":      gameIDStr,
			"status":      "active",
			"side":        playerColor,
			"mode":        string(mode),
			"difficulty":  difficulty,
			"timeControl": timeControl,
			"fen":         activeGame.CurrentFEN,
		})

		// Trigger computer move if computer is white (in background)
		go func() {
			if err := h.manager.HandleComputerMove(context.Background(), gameIDStr); err != nil {
				log.Printf("CreateGame: Computer move failed: %v", err)
			}
		}()

		return nil
	}

	// For human vs human, wait for second player
	log.Printf("CreateGame: Game %s created successfully, waiting for opponent", gameIDStr)

	// 9. Send success response
	websocket.SendSuccessResponse(client, msg.ID, map[string]interface{}{
		"gameId":      gameIDStr,
		"status":      "waiting",
		"side":        playerColor,
		"mode":        string(mode),
		"timeControl": timeControl,
		"fen":         h.manager.GetChessService().GetStartingPosition(),
	})

	return nil
}
