// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (user_id, pgn, title)
VALUES ($1, $2, $3)
RETURNING id, user_id, pgn, title, status, created_at, updated_at
`

type CreateGameParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Pgn    string      `json:"pgn"`
	Title  pgtype.Text `json:"title"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, arg.UserID, arg.Pgn, arg.Title)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Pgn,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT id, user_id, pgn, title, status, created_at, updated_at FROM games
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Pgn,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserGames = `-- name: ListUserGames :many
SELECT id, user_id, pgn, title, status, created_at, updated_at FROM games
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserGames(ctx context.Context, userID pgtype.UUID) ([]Game, error) {
	rows, err := q.db.Query(ctx, listUserGames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Pgn,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGamePGN = `-- name: UpdateGamePGN :exec
UPDATE games
SET pgn = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateGamePGNParams struct {
	ID  pgtype.UUID `json:"id"`
	Pgn string      `json:"pgn"`
}

func (q *Queries) UpdateGamePGN(ctx context.Context, arg UpdateGamePGNParams) error {
	_, err := q.db.Exec(ctx, updateGamePGN, arg.ID, arg.Pgn)
	return err
}
