// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Pgn       string           `json:"pgn"`
	Title     pgtype.Text      `json:"title"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Move struct {
	ID         pgtype.UUID      `json:"id"`
	GameID     pgtype.UUID      `json:"game_id"`
	MoveNumber int32            `json:"move_number"`
	MoveSan    string           `json:"move_san"`
	MoveUci    string           `json:"move_uci"`
	Fen        string           `json:"fen"`
	Analysis   []byte           `json:"analysis"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID      `json:"id"`
	Email     string           `json:"email"`
	Username  string           `json:"username"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
