// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetGame(ctx context.Context, id pgtype.UUID) (Game, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListUserGames(ctx context.Context, userID pgtype.UUID) ([]Game, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateGamePGN(ctx context.Context, arg UpdateGamePGNParams) error
}

var _ Querier = (*Queries)(nil)
